document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>串联编解码工具</title>");
document.writeln("    <style>");
document.writeln("        * {");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("            box-sizing: border-box;");
document.writeln("        }");
document.writeln("        body {");
document.writeln("            font-family: Arial, sans-serif;");
document.writeln("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);");
document.writeln("            min-height: 100vh;");
document.writeln("            padding: 20px;");
document.writeln("        }");
document.writeln("        .container {");
document.writeln("            max-width: 800px;");
document.writeln("            margin: 0 auto;");
document.writeln("            background: white;");
document.writeln("            border-radius: 10px;");
document.writeln("            padding: 30px;");
document.writeln("            box-shadow: 0 10px 30px rgba(0,0,0,0.3);");
document.writeln("        }");
document.writeln("        h1 {");
document.writeln("            text-align: center;");
document.writeln("            color: #333;");
document.writeln("            margin-bottom: 30px;");
document.writeln("        }");
document.writeln("        .section {");
document.writeln("            margin-bottom: 25px;");
document.writeln("        }");
document.writeln("        label {");
document.writeln("            display: block;");
document.writeln("            margin-bottom: 8px;");
document.writeln("            font-weight: bold;");
document.writeln("            color: #555;");
document.writeln("        }");
document.writeln("        textarea {");
document.writeln("            width: 100%;");
document.writeln("            min-height: 100px;");
document.writeln("            padding: 12px;");
document.writeln("            border: 2px solid #ddd;");
document.writeln("            border-radius: 5px;");
document.writeln("            font-size: 14px;");
document.writeln("            resize: vertical;");
document.writeln("            font-family: \'Courier New\', monospace;");
document.writeln("        }");
document.writeln("        textarea:focus {");
document.writeln("            outline: none;");
document.writeln("            border-color: #667eea;");
document.writeln("        }");
document.writeln("        .button-group {");
document.writeln("            display: flex;");
document.writeln("            gap: 10px;");
document.writeln("            margin-top: 20px;");
document.writeln("        }");
document.writeln("        button {");
document.writeln("            flex: 1;");
document.writeln("            padding: 12px 24px;");
document.writeln("            font-size: 16px;");
document.writeln("            border: none;");
document.writeln("            border-radius: 5px;");
document.writeln("            cursor: pointer;");
document.writeln("            transition: all 0.3s;");
document.writeln("            font-weight: bold;");
document.writeln("        }");
document.writeln("        .encode-btn {");
document.writeln("            background: #667eea;");
document.writeln("            color: white;");
document.writeln("        }");
document.writeln("        .encode-btn:hover {");
document.writeln("            background: #5568d3;");
document.writeln("        }");
document.writeln("        .decode-btn {");
document.writeln("            background: #764ba2;");
document.writeln("            color: white;");
document.writeln("        }");
document.writeln("        .decode-btn:hover {");
document.writeln("            background: #63408a;");
document.writeln("        }");
document.writeln("        .clear-btn {");
document.writeln("            background: #e74c3c;");
document.writeln("            color: white;");
document.writeln("        }");
document.writeln("        .clear-btn:hover {");
document.writeln("            background: #c0392b;");
document.writeln("        }");
document.writeln("        .info {");
document.writeln("            background: #f0f0f0;");
document.writeln("            padding: 15px;");
document.writeln("            border-radius: 5px;");
document.writeln("            margin-top: 20px;");
document.writeln("            font-size: 14px;");
document.writeln("            color: #666;");
document.writeln("        }");
document.writeln("        .info strong {");
document.writeln("            color: #333;");
document.writeln("        }");
document.writeln("        .loading {");
document.writeln("            text-align: center;");
document.writeln("            padding: 40px;");
document.writeln("            color: #666;");
document.writeln("        }");
document.writeln("        .spinner {");
document.writeln("            border: 4px solid #f3f3f3;");
document.writeln("            border-top: 4px solid #667eea;");
document.writeln("            border-radius: 50%;");
document.writeln("            width: 50px;");
document.writeln("            height: 50px;");
document.writeln("            animation: spin 1s linear infinite;");
document.writeln("            margin: 0 auto 20px;");
document.writeln("        }");
document.writeln("        @keyframes spin {");
document.writeln("            0% { transform: rotate(0deg); }");
document.writeln("            100% { transform: rotate(360deg); }");
document.writeln("        }");
document.writeln("        #app {");
document.writeln("            display: none;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'loading\' id=\'loading\'>");
document.writeln("            <div class=\'spinner\'></div>");
document.writeln("            <p>正在加载代码...</p>");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("        <div id=\'app\'>");
document.writeln("            <h1>🔐 串联编解码工具</h1>");
document.writeln("            ");
document.writeln("            <div class=\'section\'>");
document.writeln("                <label for=\'input\'>输入文本：</label>");
document.writeln("                <textarea id=\'input\' placeholder=\'请输入要编码或解码的文本...\'></textarea>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("            <div class=\'button-group\'>");
document.writeln("                <button class=\'encode-btn\' onclick=\'encode()\'>编码</button>");
document.writeln("                <button class=\'decode-btn\' onclick=\'decode()\'>解码</button>");
document.writeln("                <button class=\'clear-btn\' onclick=\'clearAll()\'>清空</button>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("            <div class=\'section\'>");
document.writeln("                <label for=\'output\'>输出结果：</label>");
document.writeln("                <textarea id=\'output\' readonly placeholder=\'结果将显示在这里...\'></textarea>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("    <canvas id=\'canvas\' style=\'display: none;\'></canvas>");
document.writeln("    ");
document.writeln("    <script>");
document.writeln("        (function() {");
document.writeln("            // 反调试保护");
document.writeln("            (() => {");
document.writeln("                function block() {");
document.writeln("                    setInterval(() => {");
document.writeln("                        Function(\'debugger\')();");
document.writeln("                    }, 50);");
document.writeln("                }");
document.writeln("                try {");
document.writeln("                    block();");
document.writeln("                } catch (err) {}");
document.writeln("            })();");
document.writeln("            ");
document.writeln("            // 图片URL");
document.writeln("            const IMAGE_URL = \'https://raw.githubusercontent.com/xiaomayisjh/share/refs/heads/main/steganography_image.png\';");
document.writeln("            ");
document.writeln("            // 解码辅助函数（仅用于提取）");
document.writeln("            const _reverseMap = {");
document.writeln("                \'Q\': \'A\', \'W\': \'B\', \'E\': \'C\', \'R\': \'D\', \'T\': \'E\', \'Y\': \'F\', \'U\': \'G\', \'I\': \'H\',");
document.writeln("                \'O\': \'I\', \'P\': \'J\', \'A\': \'K\', \'S\': \'L\', \'D\': \'M\', \'F\': \'N\', \'G\': \'O\', \'H\': \'P\',");
document.writeln("                \'J\': \'Q\', \'K\': \'R\', \'L\': \'S\', \'Z\': \'T\', \'X\': \'U\', \'C\': \'V\', \'V\': \'W\', \'B\': \'X\',");
document.writeln("                \'N\': \'Y\', \'M\': \'Z\', \'q\': \'a\', \'w\': \'b\', \'e\': \'c\', \'r\': \'d\', \'t\': \'e\', \'y\': \'f\',");
document.writeln("                \'u\': \'g\', \'i\': \'h\', \'o\': \'i\', \'p\': \'j\', \'a\': \'k\', \'s\': \'l\', \'d\': \'m\', \'f\': \'n\',");
document.writeln("                \'g\': \'o\', \'h\': \'p\', \'j\': \'q\', \'k\': \'r\', \'l\': \'s\', \'z\': \'t\', \'x\': \'u\', \'c\': \'v\',");
document.writeln("                \'v\': \'w\', \'b\': \'x\', \'n\': \'y\', \'m\': \'z\', \'5\': \'0\', \'6\': \'1\', \'7\': \'2\', \'8\': \'3\',");
document.writeln("                \'9\': \'4\', \'0\': \'5\', \'1\': \'6\', \'2\': \'7\', \'3\': \'8\', \'4\': \'9\', \'-\': \'+\', \'_\': \'/\',");
document.writeln("                \'=\': \'=\'");
document.writeln("            };");
document.writeln("            ");
document.writeln("            function _hexToString(hex) {");
document.writeln("                const bytes = new Uint8Array(hex.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));");
document.writeln("                return new TextDecoder().decode(bytes);");
document.writeln("            }");
document.writeln("            ");
document.writeln("            function _base64Decode(str) {");
document.writeln("                const binary = atob(str);");
document.writeln("                const bytes = new Uint8Array(binary.length);");
document.writeln("                for (let i = 0; i < binary.length; i++) {");
document.writeln("                    bytes[i] = binary.charCodeAt(i);");
document.writeln("                }");
document.writeln("                return new TextDecoder().decode(bytes);");
document.writeln("            }");
document.writeln("            ");
document.writeln("            function _privateDecode(str) {");
document.writeln("                return str.split(\'\').map(char => _reverseMap[char] || char).join(\'\');");
document.writeln("            }");
document.writeln("            ");
document.writeln("            function _decodeHiddenText(encodedStr) {");
document.writeln("                let step1 = _hexToString(encodedStr);");
document.writeln("                let step2 = _base64Decode(step1);");
document.writeln("                let step3 = _privateDecode(step2);");
document.writeln("                let step4 = _base64Decode(step3);");
document.writeln("                let step5 = _hexToString(step4);");
document.writeln("                return step5;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            function _binaryToText(binary) {");
document.writeln("                let text = \'\';");
document.writeln("                for (let i = 0; i < binary.length; i += 8) {");
document.writeln("                    const byte = binary.substr(i, 8);");
document.writeln("                    text += String.fromCharCode(parseInt(byte, 2));");
document.writeln("                }");
document.writeln("                return text;");
document.writeln("            }");
document.writeln("            ");
document.writeln("            // 从图片中提取代码");
document.writeln("            function extractCodeFromImage(imageUrl) {");
document.writeln("                return new Promise((resolve, reject) => {");
document.writeln("                    const img = new Image();");
document.writeln("                    img.crossOrigin = \'anonymous\';");
document.writeln("                    ");
document.writeln("                    img.onload = function() {");
document.writeln("                        try {");
document.writeln("                            const canvas = document.getElementById(\'canvas\');");
document.writeln("                            const ctx = canvas.getContext(\'2d\');");
document.writeln("                            ");
document.writeln("                            canvas.width = img.width;");
document.writeln("                            canvas.height = img.height;");
document.writeln("                            ");
document.writeln("                            ctx.drawImage(img, 0, 0);");
document.writeln("                            ");
document.writeln("                            const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);");
document.writeln("                            const data = imageData.data;");
document.writeln("                            ");
document.writeln("                            // 读取长度（前32位）");
document.writeln("                            let lengthBinary = \'\';");
document.writeln("                            for (let i = 0; i < 32; i++) {");
document.writeln("                                lengthBinary += (data[i * 4] & 1).toString();");
document.writeln("                            }");
document.writeln("                            const textLength = parseInt(lengthBinary, 2);");
document.writeln("                            ");
document.writeln("                            if (textLength <= 0 || textLength > data.length * 4) {");
document.writeln("                                reject(new Error(\'图片中没有隐藏数据或数据已损坏\'));");
document.writeln("                                return;");
document.writeln("                            }");
document.writeln("                            ");
document.writeln("                            // 读取文本数据");
document.writeln("                            let binaryText = \'\';");
document.writeln("                            for (let i = 32; i < 32 + textLength; i++) {");
document.writeln("                                binaryText += (data[i * 4] & 1).toString();");
document.writeln("                            }");
document.writeln("                            ");
document.writeln("                            const encodedText = _binaryToText(binaryText);");
document.writeln("                            const decodedCode = _decodeHiddenText(encodedText);");
document.writeln("                            ");
document.writeln("                            resolve(decodedCode);");
document.writeln("                            ");
document.writeln("                        } catch (error) {");
document.writeln("                            reject(error);");
document.writeln("                        }");
document.writeln("                    };");
document.writeln("                    ");
document.writeln("                    img.onerror = function() {");
document.writeln("                        reject(new Error(\'无法加载图片\'));");
document.writeln("                    };");
document.writeln("                    ");
document.writeln("                    img.src = imageUrl;");
document.writeln("                });");
document.writeln("            }");
document.writeln("            ");
document.writeln("            // 页面加载时从图片提取并执行代码");
document.writeln("            window.addEventListener(\'DOMContentLoaded\', async function() {");
document.writeln("                try {");
document.writeln("                    let code = await extractCodeFromImage(IMAGE_URL);");
document.writeln("                    ");
document.writeln("                    // 使用间接eval在全局作用域执行");
document.writeln("                    (0, eval)(code);");
document.writeln("                    ");
document.writeln("                    // 清除代码");
document.writeln("                    code = null;");
document.writeln("                    ");
document.writeln("                    // 隐藏加载提示，显示应用");
document.writeln("                    document.getElementById(\'loading\').style.display = \'none\';");
document.writeln("                    document.getElementById(\'app\').style.display = \'block\';");
document.writeln("                    ");
document.writeln("                } catch (error) {");
document.writeln("                    document.getElementById(\'loading\').innerHTML = ");
document.writeln("                        \'<p style=\'color: #e74c3c;\'>❌ 加载失败：\' + error.message + \'</p>\';");
document.writeln("                    console.error(\'加载失败：\', error);");
document.writeln("                }");
document.writeln("            });");
document.writeln("        })();");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
